config/routes.rb
require 'sidekiq/web'

UDiscoverMe::Application.routes.draw do
  resources :sessions

  resources :articles
  root to: 'articles#index'

  match '/landing', :to => redirect('/public/landing.html'), via: %i(get)
  match '/v1/tags/', to: 'tags#index', via: %i(get)
  match '/:id', to: 'favorites#index', via: %i(get)
  match '/favorites/:belongs_to', to: 'favorites#index', via: %i(get)
  match '/favorites', to: 'favorites#save', via: %i(post)  
  match '/auth/twitter/callback' ,to: 'sessions#create' , via: %i(get post)
  match '/delete/session', to: 'sessions#destroy', as: 'signout', via: %i(get)
  mount Sidekiq::Web, at: "/sidekiq"

  

end

app/models/article.rb
class Article
  include Mongoid::Document
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if current_user.nil?
      redirect_to "/landing"
    else
      @articles = Article.all
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params[:article]
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="main-header">
  <div class="header">
  <ul class="nav nav-pills pull-right">

  <% if current_user %>
    <li> <%= link_to "Sign out", signout_path %> </li>
  <% else %>     
    <li><%= link_to "Sign in with Twitter", "/landing" %> </li>
  <% end %>
  </ul>

  <div id = "pagehead">
    
  </div>
    
<a href="https://twitter.com/share" class="twitter-share-button" data-text="#udiscoverme Find my social identity and discover content from me at http://www.udiscover.me" data-size="large" class="pull-right">Tweet</a>
</div>



</div>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>


<div id = "tagcloud">
  
</div>
<div id="container">
  
</div>

<div id="communitycontainer">
  
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>